spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres # Ersetzen Sie <datenbankname> durch den Namen Ihrer PostgreSQL-Datenbank
    driver-class-name: org.postgresql.Driver
    username: postgres # Ersetzen Sie <benutzername> durch Ihren PostgreSQL-Benutzernamen
    password: 99Etnies+ # Ersetzen Sie <passwort> durch Ihr PostgreSQL-Passwort
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
jwt:
  expiration: 86400000
